application: 8p73ex
version: 1
runtime: go
api_version: go1

handlers:
  - url: /
    script: _go_app
    login: required
  - url: /(add|list|get|delete)
    script: _go_app
    login: required
  - url: /(.*\.(html|png|css|js|ico))
    static_files: static/\1
    upload: static/(.*\.(html|png|css|js|ico))
    login: required